### ISSUE TITLE
LUT meaning

### ISSUE THREAD

**Issue by adahbingee** [aparis69/MarchingCubeCpp#5]
great works, is there any reference for the LUT usage?

How slab_inds works for non-duplicating vertex? 
I mean why (nx * ny * 2) is enough for contain all vertices? Is it indenpent from nz?

```c++
mcVec3i* slab_inds = new mcVec3i[nx * ny * 2];
```

thanks a lot

**Comment by aparis69** [comment]
Hi!

Thank you. To be honest, I never looked into the details how the implementation and just made some quick adjustments for it to be usable in a header-only context. So, I don't have an answer. 

The code is based on [this public domain implementation](https://github.com/nsf/mc), so I think it would be best to ask the author directly!
